name: Hello GitHub Actions
on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Hello from GitHub Actions!"
      - name: Echo name
        run: echo "Chhavi"
      - name: Show date
        run: date
      - name: Show operating system
        run: uname -a
      - name: Use secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Secret is: $MY_SECRET"
          echo "Secret length: ${#MY_SECRET}"
